name: deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Node.JS version from package.json
        id: get-node-version
        run: echo ::set-output name=node::$(jq -r .engines.node ./package.json)

      - name: Get Pnpm version from package.json
        id: get-pnpm-version
        run: echo ::set-output name=node::$(jq -r .engines.pnpm ./package.json)

      - name: Use Node.js ${{steps.get-node-version.outputs.node}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{steps.get-node-version.outputs.node}}

      - name: Install PNPM ${{steps.get-pnpm-version.outputs.node}}
        run: npm i -g pnpm@${{steps.get-pnpm-version.outputs.node}}

      - name: Install dependencies
        run: |
          pnpm i
          pnpm i gh-pages

      - name: Run Type Check
        run: pnpm type-check

      - name: Run linter
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Build app
        run: pnpm run build

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pnpm run deploy -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
