name: pr-check

on:
  pull_request_target:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from PR branch
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get Node.JS version from package.json
        id: get-node-version
        run: echo ::set-output name=node::$(jq -r .engines.node ./package.json)

      - name: Get Pnpm version from package.json
        id: get-pnpm-version
        run: echo ::set-output name=node::$(jq -r .engines.pnpm ./package.json)

      - name: Use Node.js ${{steps.get-node-version.outputs.node}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{steps.get-node-version.outputs.node}}

      - name: Install PNPM ${{steps.get-pnpm-version.outputs.node}}
        run: npm i -g pnpm@${{steps.get-pnpm-version.outputs.node}}

      - name: Install dependencies
        run: |
          pnpm i
          pnpm i gh-pages

      - name: Run tests
        run: pnpm test

      - name: Build app
        run: pnpm run build
